// Comprehensive city/municipality → province mapping
// Province names match canonical names in geo-mapping.ts

// ---------------------------------------------------------------------------
// Belgium – all municipalities grouped by province
// Includes both current (post-2025 merger) and pre-merger names,
// plus common French/English alternate spellings.
// ---------------------------------------------------------------------------

const BELGIUM_CITY_MAP: Record<string, string> = {
  // ── Antwerpen (70 municipalities) ──────────────────────────────────────
  "antwerpen": "Antwerpen",
  "anvers": "Antwerpen",        // French name
  "antwerp": "Antwerpen",       // English name
  "aartselaar": "Antwerpen",
  "arendonk": "Antwerpen",
  "baarle-hertog": "Antwerpen",
  "balen": "Antwerpen",
  "beerse": "Antwerpen",
  "berlaar": "Antwerpen",
  "boechout": "Antwerpen",
  "bonheiden": "Antwerpen",
  "boom": "Antwerpen",
  "bornem": "Antwerpen",
  "borsbeek": "Antwerpen",      // merged into Antwerpen 2025
  "brasschaat": "Antwerpen",
  "brecht": "Antwerpen",
  "dessel": "Antwerpen",
  "duffel": "Antwerpen",
  "edegem": "Antwerpen",
  "essen": "Antwerpen",
  "geel": "Antwerpen",
  "grobbendonk": "Antwerpen",
  "heist-op-den-berg": "Antwerpen",
  "hemiksem": "Antwerpen",
  "herentals": "Antwerpen",
  "herenthout": "Antwerpen",
  "herselt": "Antwerpen",
  "hoogstraten": "Antwerpen",
  "hove": "Antwerpen",
  "hulshout": "Antwerpen",
  "kalmthout": "Antwerpen",
  "kapellen": "Antwerpen",
  "kasterlee": "Antwerpen",
  "kontich": "Antwerpen",
  "laakdal": "Antwerpen",
  "lier": "Antwerpen",
  "lille": "Antwerpen",
  "lint": "Antwerpen",
  "malle": "Antwerpen",
  "mechelen": "Antwerpen",
  "malines": "Antwerpen",       // French name for Mechelen
  "meerhout": "Antwerpen",
  "merksplas": "Antwerpen",
  "mol": "Antwerpen",
  "mortsel": "Antwerpen",
  "niel": "Antwerpen",
  "nijlen": "Antwerpen",
  "olen": "Antwerpen",
  "oud-turnhout": "Antwerpen",
  "putte": "Antwerpen",
  "puurs-sint-amands": "Antwerpen",
  "puurs": "Antwerpen",
  "sint-amands": "Antwerpen",
  "ranst": "Antwerpen",
  "ravels": "Antwerpen",
  "retie": "Antwerpen",
  "rijkevorsel": "Antwerpen",
  "rumst": "Antwerpen",
  "schelle": "Antwerpen",
  "schilde": "Antwerpen",
  "schoten": "Antwerpen",
  "sint-katelijne-waver": "Antwerpen",
  "stabroek": "Antwerpen",
  "turnhout": "Antwerpen",
  "vorselaar": "Antwerpen",
  "vosselaar": "Antwerpen",
  "westerlo": "Antwerpen",
  "wijnegem": "Antwerpen",
  "willebroek": "Antwerpen",
  "wommelgem": "Antwerpen",
  "wuustwezel": "Antwerpen",
  "zandhoven": "Antwerpen",
  "zoersel": "Antwerpen",
  "zwijndrecht": "Antwerpen",   // moved to Oost-Vlaanderen in 2025 merger but keep both

  // ── Oost-Vlaanderen (65 municipalities) ────────────────────────────────
  "aalst": "Oost-Vlaanderen",
  "alost": "Oost-Vlaanderen",   // French name
  "aalter": "Oost-Vlaanderen",
  "assenede": "Oost-Vlaanderen",
  "berlare": "Oost-Vlaanderen",
  "beveren": "Oost-Vlaanderen",
  "beveren-kruibeke-zwijndrecht": "Oost-Vlaanderen",
  "kruibeke": "Oost-Vlaanderen",
  "brakel": "Oost-Vlaanderen",
  "buggenhout": "Oost-Vlaanderen",
  "deinze": "Oost-Vlaanderen",
  "denderleeuw": "Oost-Vlaanderen",
  "dendermonde": "Oost-Vlaanderen",
  "termonde": "Oost-Vlaanderen", // French name for Dendermonde
  "destelbergen": "Oost-Vlaanderen",
  "eeklo": "Oost-Vlaanderen",
  "erpe-mere": "Oost-Vlaanderen",
  "evergem": "Oost-Vlaanderen",
  "gavere": "Oost-Vlaanderen",
  "gent": "Oost-Vlaanderen",
  "gand": "Oost-Vlaanderen",    // French name
  "ghent": "Oost-Vlaanderen",   // English name
  "geraardsbergen": "Oost-Vlaanderen",
  "grammont": "Oost-Vlaanderen", // French name for Geraardsbergen
  "haaltert": "Oost-Vlaanderen",
  "hamme": "Oost-Vlaanderen",
  "herzele": "Oost-Vlaanderen",
  "horebeke": "Oost-Vlaanderen",
  "kaprijke": "Oost-Vlaanderen",
  "kluisbergen": "Oost-Vlaanderen",
  "kruisem": "Oost-Vlaanderen",
  "laarne": "Oost-Vlaanderen",
  "lebbeke": "Oost-Vlaanderen",
  "lede": "Oost-Vlaanderen",
  "lierde": "Oost-Vlaanderen",
  "lievegem": "Oost-Vlaanderen",
  "lochristi": "Oost-Vlaanderen",
  "lokeren": "Oost-Vlaanderen",
  "maarkedal": "Oost-Vlaanderen",
  "maldegem": "Oost-Vlaanderen",
  "melle": "Oost-Vlaanderen",
  "merelbeke": "Oost-Vlaanderen",
  "merelbeke-melle": "Oost-Vlaanderen",
  "moerbeke": "Oost-Vlaanderen",
  "nazareth": "Oost-Vlaanderen",
  "de pinte": "Oost-Vlaanderen",
  "nazareth-de pinte": "Oost-Vlaanderen",
  "ninove": "Oost-Vlaanderen",
  "oosterzele": "Oost-Vlaanderen",
  "oudenaarde": "Oost-Vlaanderen",
  "audenarde": "Oost-Vlaanderen", // French name
  "ronse": "Oost-Vlaanderen",
  "renaix": "Oost-Vlaanderen",  // French name for Ronse
  "sint-gillis-waas": "Oost-Vlaanderen",
  "sint-laureins": "Oost-Vlaanderen",
  "sint-lievens-houtem": "Oost-Vlaanderen",
  "sint-martens-latem": "Oost-Vlaanderen",
  "sint-niklaas": "Oost-Vlaanderen",
  // saint-nicolas is under Liège (Sint-Niklaas is the Oost-Vlaanderen entry)
  "stekene": "Oost-Vlaanderen",
  "temse": "Oost-Vlaanderen",
  "waasmunster": "Oost-Vlaanderen",
  "wachtebeke": "Oost-Vlaanderen",
  "wetteren": "Oost-Vlaanderen",
  "wichelen": "Oost-Vlaanderen",
  "wortegem-petegem": "Oost-Vlaanderen",
  "zele": "Oost-Vlaanderen",
  "zelzate": "Oost-Vlaanderen",
  "zottegem": "Oost-Vlaanderen",
  "zulte": "Oost-Vlaanderen",
  "zwalm": "Oost-Vlaanderen",

  // ── West-Vlaanderen (64 municipalities) ────────────────────────────────
  "alveringem": "West-Vlaanderen",
  "anzegem": "West-Vlaanderen",
  "ardooie": "West-Vlaanderen",
  "avelgem": "West-Vlaanderen",
  "beernem": "West-Vlaanderen",
  "blankenberge": "West-Vlaanderen",
  "bredene": "West-Vlaanderen",
  "brugge": "West-Vlaanderen",
  "bruges": "West-Vlaanderen",   // French/English name
  "damme": "West-Vlaanderen",
  "de haan": "West-Vlaanderen",
  "de panne": "West-Vlaanderen",
  "la panne": "West-Vlaanderen", // French name
  "deerlijk": "West-Vlaanderen",
  "dentergem": "West-Vlaanderen",
  "diksmuide": "West-Vlaanderen",
  "dixmude": "West-Vlaanderen",  // French name
  "gistel": "West-Vlaanderen",
  "harelbeke": "West-Vlaanderen",
  "heuvelland": "West-Vlaanderen",
  "hooglede": "West-Vlaanderen",
  "houthulst": "West-Vlaanderen",
  "ichtegem": "West-Vlaanderen",
  "ieper": "West-Vlaanderen",
  "ypres": "West-Vlaanderen",    // French/English name
  "ingelmunster": "West-Vlaanderen",
  "izegem": "West-Vlaanderen",
  "jabbeke": "West-Vlaanderen",
  "knokke-heist": "West-Vlaanderen",
  "knokke": "West-Vlaanderen",
  "koekelare": "West-Vlaanderen",
  "koksijde": "West-Vlaanderen",
  "coxyde": "West-Vlaanderen",   // French name
  "kortemark": "West-Vlaanderen",
  "kortrijk": "West-Vlaanderen",
  "courtrai": "West-Vlaanderen", // French name
  "kuurne": "West-Vlaanderen",
  "langemark-poelkapelle": "West-Vlaanderen",
  "langemark": "West-Vlaanderen",
  "ledegem": "West-Vlaanderen",
  "lendelede": "West-Vlaanderen",
  "lichtervelde": "West-Vlaanderen",
  "lo-reninge": "West-Vlaanderen",
  "menen": "West-Vlaanderen",
  "menin": "West-Vlaanderen",    // French name
  "mesen": "West-Vlaanderen",
  "messines": "West-Vlaanderen", // French name
  "meulebeke": "West-Vlaanderen", // merged into Tielt 2025
  "middelkerke": "West-Vlaanderen",
  "moorslede": "West-Vlaanderen",
  "nieuwpoort": "West-Vlaanderen",
  "oostende": "West-Vlaanderen",
  "ostende": "West-Vlaanderen",  // French name
  "ostend": "West-Vlaanderen",   // English name
  "oostkamp": "West-Vlaanderen",
  "oostrozebeke": "West-Vlaanderen",
  "oudenburg": "West-Vlaanderen",
  "pittem": "West-Vlaanderen",
  "poperinge": "West-Vlaanderen",
  "roeselare": "West-Vlaanderen",
  "roulers": "West-Vlaanderen",  // French name
  "ruiselede": "West-Vlaanderen", // merged into Wingene 2025
  "spiere-helkijn": "West-Vlaanderen",
  "staden": "West-Vlaanderen",
  "tielt": "West-Vlaanderen",
  "torhout": "West-Vlaanderen",
  "veurne": "West-Vlaanderen",
  "furnes": "West-Vlaanderen",   // French name
  "vleteren": "West-Vlaanderen",
  "waregem": "West-Vlaanderen",
  "wervik": "West-Vlaanderen",
  "wevelgem": "West-Vlaanderen",
  "wielsbeke": "West-Vlaanderen",
  "wingene": "West-Vlaanderen",
  "zedelgem": "West-Vlaanderen",
  "zonnebeke": "West-Vlaanderen",
  "zuienkerke": "West-Vlaanderen",
  "zwevegem": "West-Vlaanderen",

  // ── Vlaams-Brabant (65 municipalities) ─────────────────────────────────
  // Halle-Vilvoorde arrondissement
  "affligem": "Vlaams-Brabant",
  "asse": "Vlaams-Brabant",
  "beersel": "Vlaams-Brabant",
  "bever": "Vlaams-Brabant",
  "dilbeek": "Vlaams-Brabant",
  "drogenbos": "Vlaams-Brabant",
  "galmaarden": "Vlaams-Brabant", // merged into Pajottegem 2025
  "gooik": "Vlaams-Brabant",      // merged into Pajottegem 2025
  "grimbergen": "Vlaams-Brabant",
  "halle": "Vlaams-Brabant",
  "hal": "Vlaams-Brabant",        // French name
  "herne": "Vlaams-Brabant",      // merged into Pajottegem 2025
  "hoeilaart": "Vlaams-Brabant",
  "kampenhout": "Vlaams-Brabant",
  "kapelle-op-den-bos": "Vlaams-Brabant",
  "kraainem": "Vlaams-Brabant",
  "lennik": "Vlaams-Brabant",
  "liedekerke": "Vlaams-Brabant",
  "linkebeek": "Vlaams-Brabant",
  "londerzeel": "Vlaams-Brabant",
  "machelen": "Vlaams-Brabant",
  "meise": "Vlaams-Brabant",
  "merchtem": "Vlaams-Brabant",
  "opwijk": "Vlaams-Brabant",
  "overijse": "Vlaams-Brabant",
  "pajottegem": "Vlaams-Brabant", // 2025 merger of Galmaarden+Gooik+Herne
  "pepingen": "Vlaams-Brabant",
  "roosdaal": "Vlaams-Brabant",
  "sint-genesius-rode": "Vlaams-Brabant",
  "rhode-saint-genèse": "Vlaams-Brabant", // French name
  "sint-pieters-leeuw": "Vlaams-Brabant",
  "steenokkerzeel": "Vlaams-Brabant",
  "ternat": "Vlaams-Brabant",
  "vilvoorde": "Vlaams-Brabant",
  "vilvorde": "Vlaams-Brabant",  // French name
  "wemmel": "Vlaams-Brabant",
  "wezembeek-oppem": "Vlaams-Brabant",
  "zaventem": "Vlaams-Brabant",
  "zemst": "Vlaams-Brabant",
  // Leuven arrondissement
  "aarschot": "Vlaams-Brabant",
  "begijnendijk": "Vlaams-Brabant",
  "bekkevoort": "Vlaams-Brabant",
  "bertem": "Vlaams-Brabant",
  "bierbeek": "Vlaams-Brabant",
  "boortmeerbeek": "Vlaams-Brabant",
  "boutersem": "Vlaams-Brabant",
  "diest": "Vlaams-Brabant",
  "geetbets": "Vlaams-Brabant",
  "glabbeek": "Vlaams-Brabant",
  "haacht": "Vlaams-Brabant",
  "herent": "Vlaams-Brabant",
  "hoegaarden": "Vlaams-Brabant",
  "holsbeek": "Vlaams-Brabant",
  "huldenberg": "Vlaams-Brabant",
  "keerbergen": "Vlaams-Brabant",
  "kortenaken": "Vlaams-Brabant",
  "kortenberg": "Vlaams-Brabant",
  "landen": "Vlaams-Brabant",
  "leuven": "Vlaams-Brabant",
  "louvain": "Vlaams-Brabant",  // French name
  "linter": "Vlaams-Brabant",
  "lubbeek": "Vlaams-Brabant",
  "oud-heverlee": "Vlaams-Brabant",
  "rotselaar": "Vlaams-Brabant",
  "scherpenheuvel-zichem": "Vlaams-Brabant",
  "scherpenheuvel": "Vlaams-Brabant",
  "tervuren": "Vlaams-Brabant",
  "tielt-winge": "Vlaams-Brabant",
  "tienen": "Vlaams-Brabant",
  "tirlemont": "Vlaams-Brabant", // French name for Tienen
  "tremelo": "Vlaams-Brabant",
  "zoutleeuw": "Vlaams-Brabant",
  "léau": "Vlaams-Brabant",     // French name for Zoutleeuw

  // ── Limburg (42 municipalities) ────────────────────────────────────────
  "alken": "Limburg",
  "as": "Limburg",
  "beringen": "Limburg",
  "bilzen": "Limburg",
  "bilzen-hoeselt": "Limburg",
  "hoeselt": "Limburg",         // merged into Bilzen 2025
  "bocholt": "Limburg",
  "borgloon": "Limburg",        // merged into Tongeren 2025
  "bree": "Limburg",
  "diepenbeek": "Limburg",
  "dilsen-stokkem": "Limburg",
  "genk": "Limburg",
  "gingelom": "Limburg",
  "halen": "Limburg",
  "ham": "Limburg",             // merged into Tessenderlo 2025
  "hamont-achel": "Limburg",
  "hasselt": "Limburg",
  "hechtel-eksel": "Limburg",
  "heers": "Limburg",
  "herk-de-stad": "Limburg",
  "herstappe": "Limburg",
  "heusden-zolder": "Limburg",
  "houthalen-helchteren": "Limburg",
  "kinrooi": "Limburg",
  "kortessem": "Limburg",       // merged into Hasselt 2025
  "lanaken": "Limburg",
  "leopoldsburg": "Limburg",
  "lommel": "Limburg",
  "lummen": "Limburg",
  "maaseik": "Limburg",
  "maasmechelen": "Limburg",
  "nieuwerkerken": "Limburg",
  "oudsbergen": "Limburg",
  "peer": "Limburg",
  "pelt": "Limburg",
  "riemst": "Limburg",
  "sint-truiden": "Limburg",
  "saint-trond": "Limburg",     // French name
  "tessenderlo": "Limburg",
  "tessenderlo-ham": "Limburg",
  "tongeren": "Limburg",
  "tongeren-borgloon": "Limburg",
  "tongres": "Limburg",         // French name
  "voeren": "Limburg",
  "fourons": "Limburg",         // French name for Voeren
  "wellen": "Limburg",
  "zonhoven": "Limburg",
  "zutendaal": "Limburg",

  // ── Brussels Capital Region (19 municipalities) ────────────────────────
  "brussel": "Brussels",
  "bruxelles": "Brussels",
  "brussels": "Brussels",
  "anderlecht": "Brussels",
  "auderghem": "Brussels",
  "oudergem": "Brussels",       // Dutch name
  "berchem-sainte-agathe": "Brussels",
  "sint-agatha-berchem": "Brussels",
  "etterbeek": "Brussels",
  "evere": "Brussels",
  "forest": "Brussels",
  "vorst": "Brussels",          // Dutch name
  "ganshoren": "Brussels",
  "ixelles": "Brussels",
  "elsene": "Brussels",         // Dutch name
  "jette": "Brussels",
  "koekelberg": "Brussels",
  "molenbeek-saint-jean": "Brussels",
  "sint-jans-molenbeek": "Brussels",
  "molenbeek": "Brussels",
  "saint-gilles": "Brussels",
  "sint-gillis": "Brussels",    // Dutch name
  "saint-josse-ten-noode": "Brussels",
  "sint-joost-ten-node": "Brussels",
  "schaerbeek": "Brussels",
  "schaarbeek": "Brussels",     // Dutch name
  "uccle": "Brussels",
  "ukkel": "Brussels",          // Dutch name
  "watermael-boitsfort": "Brussels",
  "watermaal-bosvoorde": "Brussels",
  "woluwe-saint-lambert": "Brussels",
  "sint-lambrechts-woluwe": "Brussels",
  "woluwe-saint-pierre": "Brussels",
  "sint-pieters-woluwe": "Brussels",

  // ── Hainaut (69 municipalities) ────────────────────────────────────────
  "aiseau-presles": "Hainaut",
  "anderlues": "Hainaut",
  "antoing": "Hainaut",
  "ath": "Hainaut",
  "beaumont": "Hainaut",
  "belœil": "Hainaut",
  "beloeil": "Hainaut",
  "bernissart": "Hainaut",
  "binche": "Hainaut",
  "boussu": "Hainaut",
  "braine-le-comte": "Hainaut",
  "brugelette": "Hainaut",
  "brunehaut": "Hainaut",
  "celles": "Hainaut",
  "chapelle-lez-herlaimont": "Hainaut",
  "charleroi": "Hainaut",
  "châtelet": "Hainaut",
  "chatelet": "Hainaut",
  "chièvres": "Hainaut",
  "chievres": "Hainaut",
  "chimay": "Hainaut",
  "colfontaine": "Hainaut",
  "comines-warneton": "Hainaut",
  "comines": "Hainaut",
  "courcelles": "Hainaut",
  "dour": "Hainaut",
  "écaussinnes": "Hainaut",
  "ecaussinnes": "Hainaut",
  "ellezelles": "Hainaut",
  "enghien": "Hainaut",
  "edingen": "Hainaut",         // Dutch name for Enghien
  "erquelinnes": "Hainaut",
  "estaimpuis": "Hainaut",
  "estinnes": "Hainaut",
  "farciennes": "Hainaut",
  "fleurus": "Hainaut",
  "flobecq": "Hainaut",
  "vloesberg": "Hainaut",       // Dutch name
  "fontaine-l'évêque": "Hainaut",
  "fontaine-l'eveque": "Hainaut",
  "frameries": "Hainaut",
  "frasnes-lez-anvaing": "Hainaut",
  "froidchapelle": "Hainaut",
  "gerpinnes": "Hainaut",
  "ham-sur-heure-nalinnes": "Hainaut",
  "hensies": "Hainaut",
  "honnelles": "Hainaut",
  "jurbise": "Hainaut",
  "la louvière": "Hainaut",
  "la louviere": "Hainaut",
  "le rœulx": "Hainaut",
  "le roeulx": "Hainaut",
  "lens": "Hainaut",
  "les bons villers": "Hainaut",
  "lessines": "Hainaut",
  "lessen": "Hainaut",          // Dutch name
  "leuze-en-hainaut": "Hainaut",
  "lobbes": "Hainaut",
  "manage": "Hainaut",
  "merbes-le-château": "Hainaut",
  "merbes-le-chateau": "Hainaut",
  "momignies": "Hainaut",
  "mons": "Hainaut",
  "bergen": "Hainaut",          // Dutch name for Mons
  "mont-de-l'enclus": "Hainaut",
  "montigny-le-tilleul": "Hainaut",
  "morlanwelz": "Hainaut",
  "mouscron": "Hainaut",
  "moeskroen": "Hainaut",       // Dutch name
  "pecq": "Hainaut",
  "péruwelz": "Hainaut",
  "peruwelz": "Hainaut",
  "pont-à-celles": "Hainaut",
  "pont-a-celles": "Hainaut",
  "quaregnon": "Hainaut",
  "quévy": "Hainaut",
  "quevy": "Hainaut",
  "quiévrain": "Hainaut",
  "quievrain": "Hainaut",
  "rumes": "Hainaut",
  "saint-ghislain": "Hainaut",
  "seneffe": "Hainaut",
  "silly": "Hainaut",
  "sivry-rance": "Hainaut",
  "soignies": "Hainaut",
  "zinnik": "Hainaut",          // Dutch name for Soignies
  "thuin": "Hainaut",
  "tournai": "Hainaut",
  "doornik": "Hainaut",         // Dutch name for Tournai

  // ── Liège (84 municipalities) ──────────────────────────────────────────
  "amay": "Liège",
  "amel": "Liège",
  "ans": "Liège",
  "anthisnes": "Liège",
  "aubel": "Liège",
  "awans": "Liège",
  "aywaille": "Liège",
  "baelen": "Liège",
  "bassenge": "Liège",
  "berloz": "Liège",
  "beyne-heusay": "Liège",
  "blegny": "Liège",
  "braives": "Liège",
  "büllingen": "Liège",
  "bullingen": "Liège",
  "bullange": "Liège",          // French name
  "burdinne": "Liège",
  "burg-reuland": "Liège",
  "bütgenbach": "Liège",
  "butgenbach": "Liège",
  "chaudfontaine": "Liège",
  "clavier": "Liège",
  "comblain-au-pont": "Liège",
  "crisnée": "Liège",
  "crisnee": "Liège",
  "dalhem": "Liège",
  "dison": "Liège",
  "donceel": "Liège",
  "engis": "Liège",
  "esneux": "Liège",
  "eupen": "Liège",
  "faimes": "Liège",
  "ferrières": "Liège",
  "ferrieres": "Liège",
  "fexhe-le-haut-clocher": "Liège",
  "flémalle": "Liège",
  "flemalle": "Liège",
  "fléron": "Liège",
  "fleron": "Liège",
  "geer": "Liège",
  "grâce-hollogne": "Liège",
  "grace-hollogne": "Liège",
  "hamoir": "Liège",
  "hannut": "Liège",
  "hannuit": "Liège",
  "héron": "Liège",
  "heron": "Liège",
  "herstal": "Liège",
  "herve": "Liège",
  "huy": "Liège",
  "hoei": "Liège",              // Dutch name for Huy
  "jalhay": "Liège",
  "juprelle": "Liège",
  "kelmis": "Liège",
  "la calamine": "Liège",       // French name for Kelmis
  "liège": "Liège",
  "liege": "Liège",
  "luik": "Liège",              // Dutch name
  "lierneux": "Liège",
  "limbourg": "Liège",
  "lincent": "Liège",
  "lontzen": "Liège",
  "malmedy": "Liège",
  "marchin": "Liège",
  "modave": "Liège",
  "nandrin": "Liège",
  "neupré": "Liège",
  "neupre": "Liège",
  "olne": "Liège",
  "oreye": "Liège",
  "ouffet": "Liège",
  "oupeye": "Liège",
  "pepinster": "Liège",
  "plombières": "Liège",
  "plombieres": "Liège",
  "raeren": "Liège",
  "remicourt": "Liège",
  "saint-georges-sur-meuse": "Liège",
  "saint-nicolas": "Liège",
  "sankt vith": "Liège",
  "saint-vith": "Liège",
  "seraing": "Liège",
  "soumagne": "Liège",
  "spa": "Liège",
  "sprimont": "Liège",
  "stavelot": "Liège",
  "stoumont": "Liège",
  "theux": "Liège",
  "thimister-clermont": "Liège",
  "tinlot": "Liège",
  "trois-ponts": "Liège",
  "trooz": "Liège",
  "verlaine": "Liège",
  "verviers": "Liège",
  "villers-le-bouillet": "Liège",
  "visé": "Liège",
  "vise": "Liège",
  "waimes": "Liège",
  "weismes": "Liège",           // German name
  "wanze": "Liège",
  "waremme": "Liège",
  "borgworm": "Liège",          // Dutch name for Waremme
  "wasseiges": "Liège",

  // ── Luxembourg (44 municipalities) ─────────────────────────────────────
  "arlon": "Luxembourg",
  "aarlen": "Luxembourg",       // Dutch name
  "attert": "Luxembourg",
  "aubange": "Luxembourg",
  "bastogne": "Luxembourg",
  "bastenaken": "Luxembourg",   // Dutch name
  "bertogne": "Luxembourg",     // merged into Bastogne 2025
  "bertrix": "Luxembourg",
  "bouillon": "Luxembourg",
  "chiny": "Luxembourg",
  "daverdisse": "Luxembourg",
  "durbuy": "Luxembourg",
  "érezée": "Luxembourg",
  "erezee": "Luxembourg",
  "étalle": "Luxembourg",
  "etalle": "Luxembourg",
  "fauvillers": "Luxembourg",
  "florenville": "Luxembourg",
  "gouvy": "Luxembourg",
  "habay": "Luxembourg",
  "herbeumont": "Luxembourg",
  "hotton": "Luxembourg",
  "houffalize": "Luxembourg",
  "la roche-en-ardenne": "Luxembourg",
  "léglise": "Luxembourg",
  "leglise": "Luxembourg",
  "libin": "Luxembourg",
  "libramont-chevigny": "Luxembourg",
  "libramont": "Luxembourg",
  "manhay": "Luxembourg",
  "marche-en-famenne": "Luxembourg",
  "marche": "Luxembourg",
  "martelange": "Luxembourg",
  "meix-devant-virton": "Luxembourg",
  "messancy": "Luxembourg",
  "musson": "Luxembourg",
  "nassogne": "Luxembourg",
  "neufchâteau": "Luxembourg",
  "neufchateau": "Luxembourg",
  "paliseul": "Luxembourg",
  "rendeux": "Luxembourg",
  "rouvroy": "Luxembourg",
  "saint-hubert": "Luxembourg",
  "saint-léger": "Luxembourg",
  "saint-leger": "Luxembourg",
  "sainte-ode": "Luxembourg",
  "tellin": "Luxembourg",
  "tenneville": "Luxembourg",
  "tintigny": "Luxembourg",
  "vaux-sur-sûre": "Luxembourg",
  "vaux-sur-sure": "Luxembourg",
  "vielsalm": "Luxembourg",
  "virton": "Luxembourg",
  "wellin": "Luxembourg",

  // ── Namur (38 municipalities) ──────────────────────────────────────────
  "andenne": "Namur",
  "anhée": "Namur",
  "anhee": "Namur",
  "assesse": "Namur",
  "beauraing": "Namur",
  "bièvre": "Namur",
  "bievre": "Namur",
  "cerfontaine": "Namur",
  "ciney": "Namur",
  "couvin": "Namur",
  "dinant": "Namur",
  "doische": "Namur",
  "éghezée": "Namur",
  "eghezee": "Namur",
  "fernelmont": "Namur",
  "floreffe": "Namur",
  "florennes": "Namur",
  "fosses-la-ville": "Namur",
  "gedinne": "Namur",
  "gembloux": "Namur",
  "gesves": "Namur",
  "hamois": "Namur",
  "hastière": "Namur",
  "hastiere": "Namur",
  "havelange": "Namur",
  "houyet": "Namur",
  "jemeppe-sur-sambre": "Namur",
  "la bruyère": "Namur",
  "la bruyere": "Namur",
  "mettet": "Namur",
  "namur": "Namur",
  "namen": "Namur",             // Dutch name
  "ohey": "Namur",
  "onhaye": "Namur",
  "philippeville": "Namur",
  "profondeville": "Namur",
  "rochefort": "Namur",
  "sambreville": "Namur",
  "sombreffe": "Namur",
  "somme-leuze": "Namur",
  "viroinval": "Namur",
  "vresse-sur-semois": "Namur",
  "walcourt": "Namur",
  "yvoir": "Namur",

  // ── Brabant wallon (27 municipalities) ─────────────────────────────────
  "beauvechain": "Brabant wallon",
  "bevekom": "Brabant wallon",   // Dutch name for Beauvechain
  "braine-l'alleud": "Brabant wallon",
  "eigenbrakel": "Brabant wallon", // Dutch name
  "braine-le-château": "Brabant wallon",
  "braine-le-chateau": "Brabant wallon",
  "kasteelbrakel": "Brabant wallon", // Dutch name
  "chastre": "Brabant wallon",
  "chaumont-gistoux": "Brabant wallon",
  "court-saint-étienne": "Brabant wallon",
  "court-saint-etienne": "Brabant wallon",
  "genappe": "Brabant wallon",
  "grez-doiceau": "Brabant wallon",
  "hélécine": "Brabant wallon",
  "helecine": "Brabant wallon",
  "incourt": "Brabant wallon",
  "ittre": "Brabant wallon",
  "jodoigne": "Brabant wallon",
  "geldenaken": "Brabant wallon", // Dutch name for Jodoigne
  "la hulpe": "Brabant wallon",
  "terhulpen": "Brabant wallon", // Dutch name
  "lasne": "Brabant wallon",
  "mont-saint-guibert": "Brabant wallon",
  "nivelles": "Brabant wallon",
  "nijvel": "Brabant wallon",   // Dutch name
  "orp-jauche": "Brabant wallon",
  "ottignies-louvain-la-neuve": "Brabant wallon",
  "ottignies": "Brabant wallon",
  "louvain-la-neuve": "Brabant wallon",
  "perwez": "Brabant wallon",
  "ramillies": "Brabant wallon",
  "rebecq": "Brabant wallon",
  "rixensart": "Brabant wallon",
  "tubize": "Brabant wallon",
  "villers-la-ville": "Brabant wallon",
  "walhain": "Brabant wallon",
  "waterloo": "Brabant wallon",
  "wavre": "Brabant wallon",
  "waver": "Brabant wallon",    // Dutch name
}

// ---------------------------------------------------------------------------
// France – major cities → région
// ---------------------------------------------------------------------------

const FRANCE_CITY_MAP: Record<string, string> = {
  "paris": "Île-de-France",
  "marseille": "Provence-Alpes-Côte d'Azur",
  "lyon": "Auvergne-Rhône-Alpes",
  "toulouse": "Occitanie",
  "nice": "Provence-Alpes-Côte d'Azur",
  "nantes": "Pays de la Loire",
  "montpellier": "Occitanie",
  "strasbourg": "Grand Est",
  "bordeaux": "Nouvelle-Aquitaine",
  "lille": "Hauts-de-France",
  "rennes": "Bretagne",
  "reims": "Grand Est",
  "saint-étienne": "Auvergne-Rhône-Alpes",
  "saint-etienne": "Auvergne-Rhône-Alpes",
  "toulon": "Provence-Alpes-Côte d'Azur",
  "le havre": "Normandie",
  "grenoble": "Auvergne-Rhône-Alpes",
  "dijon": "Bourgogne-Franche-Comté",
  "angers": "Pays de la Loire",
  "nîmes": "Occitanie",
  "nimes": "Occitanie",
  "clermont-ferrand": "Auvergne-Rhône-Alpes",
  "aix-en-provence": "Provence-Alpes-Côte d'Azur",
  "brest": "Bretagne",
  "tours": "Centre-Val de Loire",
  "amiens": "Hauts-de-France",
  "limoges": "Nouvelle-Aquitaine",
  "metz": "Grand Est",
  "perpignan": "Occitanie",
  "besançon": "Bourgogne-Franche-Comté",
  "besancon": "Bourgogne-Franche-Comté",
  "orléans": "Centre-Val de Loire",
  "orleans": "Centre-Val de Loire",
  "rouen": "Normandie",
  "mulhouse": "Grand Est",
  "caen": "Normandie",
  "nancy": "Grand Est",
  "saint-denis": "Île-de-France",
  "argenteuil": "Île-de-France",
  "montreuil": "Île-de-France",
  "saint-paul": "La Réunion",
  "roubaix": "Hauts-de-France",
  "tourcoing": "Hauts-de-France",
  "avignon": "Provence-Alpes-Côte d'Azur",
  "dunkerque": "Hauts-de-France",
  "dunkirk": "Hauts-de-France",
  "calais": "Hauts-de-France",
  "poitiers": "Nouvelle-Aquitaine",
  "pau": "Nouvelle-Aquitaine",
  "la rochelle": "Nouvelle-Aquitaine",
  "cannes": "Provence-Alpes-Côte d'Azur",
  "antibes": "Provence-Alpes-Côte d'Azur",
  "boulogne-billancourt": "Île-de-France",
  "versailles": "Île-de-France",
  "colombes": "Île-de-France",
  "vitry-sur-seine": "Île-de-France",
  "créteil": "Île-de-France",
  "creteil": "Île-de-France",
  "nanterre": "Île-de-France",
  "courbevoie": "Île-de-France",
  "rueil-malmaison": "Île-de-France",
  "saint-maur-des-fossés": "Île-de-France",
  "issy-les-moulineaux": "Île-de-France",
  "levallois-perret": "Île-de-France",
  "neuilly-sur-seine": "Île-de-France",
  "béziers": "Occitanie",
  "beziers": "Occitanie",
  "ajaccio": "Corse",
  "bastia": "Corse",
  "bayonne": "Nouvelle-Aquitaine",
  "valence": "Auvergne-Rhône-Alpes",
  "lorient": "Bretagne",
  "troyes": "Grand Est",
  "chambéry": "Auvergne-Rhône-Alpes",
  "chambery": "Auvergne-Rhône-Alpes",
  "annecy": "Auvergne-Rhône-Alpes",
  "chartres": "Centre-Val de Loire",
  "quimper": "Bretagne",
  "saint-brieuc": "Bretagne",
  "vannes": "Bretagne",
  "colmar": "Grand Est",
  "bourges": "Centre-Val de Loire",
  "la roche-sur-yon": "Pays de la Loire",
  "le mans": "Pays de la Loire",
  "saint-nazaire": "Pays de la Loire",
  "laval": "Pays de la Loire",
  "tarbes": "Occitanie",
  "carcassonne": "Occitanie",
  "albi": "Occitanie",
  "angoulême": "Nouvelle-Aquitaine",
  "angouleme": "Nouvelle-Aquitaine",
  "périgueux": "Nouvelle-Aquitaine",
  "perigueux": "Nouvelle-Aquitaine",
  "agen": "Nouvelle-Aquitaine",
  "niort": "Nouvelle-Aquitaine",
}

// ---------------------------------------------------------------------------
// Italy – major cities → regione
// ---------------------------------------------------------------------------

const ITALY_CITY_MAP: Record<string, string> = {
  "roma": "Lazio",
  "rome": "Lazio",
  "milano": "Lombardia",
  "milan": "Lombardia",
  "napoli": "Campania",
  "naples": "Campania",
  "torino": "Piemonte",
  "turin": "Piemonte",
  "palermo": "Sicilia",
  "genova": "Liguria",
  "genoa": "Liguria",
  "bologna": "Emilia-Romagna",
  "firenze": "Toscana",
  "florence": "Toscana",
  "bari": "Puglia",
  "catania": "Sicilia",
  "venezia": "Veneto",
  "venice": "Veneto",
  "verona": "Veneto",
  "messina": "Sicilia",
  "padova": "Veneto",
  "padua": "Veneto",
  "trieste": "Friuli Venezia Giulia",
  "brescia": "Lombardia",
  "parma": "Emilia-Romagna",
  "taranto": "Puglia",
  "prato": "Toscana",
  "modena": "Emilia-Romagna",
  "reggio calabria": "Calabria",
  "reggio emilia": "Emilia-Romagna",
  "perugia": "Umbria",
  "livorno": "Toscana",
  "ravenna": "Emilia-Romagna",
  "cagliari": "Sardegna",
  "foggia": "Puglia",
  "rimini": "Emilia-Romagna",
  "salerno": "Campania",
  "ferrara": "Emilia-Romagna",
  "sassari": "Sardegna",
  "latina": "Lazio",
  "monza": "Lombardia",
  "siracusa": "Sicilia",
  "syracuse": "Sicilia",
  "bergamo": "Lombardia",
  "pescara": "Abruzzo",
  "trento": "Trentino-Alto Adige",
  "bolzano": "Trentino-Alto Adige",
  "bozen": "Trentino-Alto Adige",
  "vicenza": "Veneto",
  "terni": "Umbria",
  "novara": "Piemonte",
  "piacenza": "Emilia-Romagna",
  "ancona": "Marche",
  "lecce": "Puglia",
  "udine": "Friuli Venezia Giulia",
  "arezzo": "Toscana",
  "pesaro": "Marche",
  "alessandria": "Piemonte",
  "catanzaro": "Calabria",
  "cosenza": "Calabria",
  "l'aquila": "Abruzzo",
  "potenza": "Basilicata",
  "como": "Lombardia",
  "lucca": "Toscana",
  "pisa": "Toscana",
  "siena": "Toscana",
  "aosta": "Valle d'Aosta",
  "campobasso": "Molise",
  "isernia": "Molise",
  "matera": "Basilicata",
}

// ---------------------------------------------------------------------------
// Lookup function
// ---------------------------------------------------------------------------

/**
 * Look up a city/municipality name and return the province (Belgium) or
 * region (France, Italy). Case-insensitive.
 *
 * @returns The canonical province/region name, or null if not found.
 */
export function cityToProvince(city: string, country: string): string | null {
  const key = city.trim().toLowerCase()
  if (!key) return null

  switch (country) {
    case "Belgium": {
      return BELGIUM_CITY_MAP[key] ?? null
    }
    case "France": {
      return FRANCE_CITY_MAP[key] ?? null
    }
    case "Italy": {
      return ITALY_CITY_MAP[key] ?? null
    }
    default:
      return null
  }
}
